#!/usr/bin/env python3
"""
LiveAzan — One-command setup script.

Usage:
    python3 setup.py              # Development setup
    python3 setup.py --production # Production setup (uses Docker)

Requirements: Python 3.10+ (stdlib only — no pip install needed)
"""

import os
import sys
import json
import shutil
import secrets
import platform
import subprocess
from pathlib import Path

ROOT_DIR = Path(__file__).parent.resolve()
SERVER_DIR = ROOT_DIR / "server"
ENV_FILE = SERVER_DIR / ".env"

# ─── Helpers ──────────────────────────────────────────────────────────────────

def run(cmd: str, cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess:
    """Run a shell command and return the result."""
    print(f"  $ {cmd}")
    return subprocess.run(cmd, shell=True, cwd=cwd or ROOT_DIR, check=check,
                          capture_output=True, text=True)

def cmd_exists(name: str) -> bool:
    return shutil.which(name) is not None

def heading(text: str) -> None:
    print(f"\n{'=' * 60}")
    print(f"  {text}")
    print(f"{'=' * 60}\n")

def success(text: str) -> None:
    print(f"  [OK] {text}")

def warn(text: str) -> None:
    print(f"  [!!] {text}")

def fail(text: str) -> None:
    print(f"  [FAIL] {text}")
    sys.exit(1)

# ─── Checks ──────────────────────────────────────────────────────────────────

def detect_os():
    heading("Detecting Operating System")
    system = platform.system()
    machine = platform.machine()
    release = platform.release()
    success(f"System: {system} {machine} ({release})")
    return system

def check_python():
    heading("Checking Python")
    v = sys.version_info
    if v.major < 3 or (v.major == 3 and v.minor < 10):
        fail(f"Python 3.10+ required, found {v.major}.{v.minor}")
    success(f"Python {v.major}.{v.minor}.{v.micro}")

def check_node():
    heading("Checking Node.js")
    if not cmd_exists("node"):
        warn("Node.js not found.")
        system = platform.system()
        if system == "Darwin":
            print("  Install: brew install node  OR  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash")
        elif system == "Linux":
            print("  Install: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash")
        else:
            print("  Install: winget install OpenJS.NodeJS.LTS")
        fail("Please install Node.js 18+ and re-run this script.")

    result = run("node --version", check=False)
    version = result.stdout.strip()
    success(f"Node.js {version}")

    if not cmd_exists("npm"):
        fail("npm not found. It should come with Node.js.")
    success("npm available")

def check_postgres():
    heading("Checking PostgreSQL")
    if not cmd_exists("psql"):
        warn("PostgreSQL not found.")
        system = platform.system()
        if system == "Darwin":
            print("  Install: brew install postgresql@16 && brew services start postgresql@16")
        elif system == "Linux":
            print("  Install: sudo apt install postgresql postgresql-contrib && sudo systemctl start postgresql")
        else:
            print("  Install: winget install PostgreSQL.PostgreSQL  OR use Docker")
        print("  Or use Docker: docker run -d --name liveaszan-pg -e POSTGRES_PASSWORD=liveaszan -p 5432:5432 postgres:16")
        fail("Please install PostgreSQL and re-run this script.")
    success("PostgreSQL available")

def check_redis():
    heading("Checking Redis")
    if not cmd_exists("redis-cli"):
        warn("Redis not found (optional — app works without it for dev).")
        system = platform.system()
        if system == "Darwin":
            print("  Install: brew install redis && brew services start redis")
        elif system == "Linux":
            print("  Install: sudo apt install redis-server && sudo systemctl start redis")
        else:
            print("  Install via Docker: docker run -d --name liveaszan-redis -p 6379:6379 redis:7")
    else:
        success("Redis available")

# ─── Setup ────────────────────────────────────────────────────────────────────

def install_dependencies():
    heading("Installing npm dependencies")
    run("npm install", cwd=ROOT_DIR)
    success("All dependencies installed")

def generate_env():
    heading("Generating .env file")
    if ENV_FILE.exists():
        warn(f".env already exists at {ENV_FILE}, skipping.")
        return

    jwt_secret = secrets.token_urlsafe(48)
    db_password = secrets.token_urlsafe(16)

    env_content = f"""# LiveAzan Server Configuration
# Auto-generated by setup.py

DATABASE_URL=postgresql://liveaszan:{db_password}@localhost:5432/liveaszan
JWT_SECRET={jwt_secret}
REDIS_URL=redis://localhost:6379
ALADHAN_API_BASE=https://api.aladhan.com/v1
PORT=3001

# OAuth credentials (fill in for production)
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# APPLE_CLIENT_ID=
# APPLE_TEAM_ID=
# APPLE_KEY_ID=
# MICROSOFT_CLIENT_ID=
# MICROSOFT_CLIENT_SECRET=
"""
    ENV_FILE.write_text(env_content)
    success(f".env created at {ENV_FILE}")
    return db_password

def setup_database(db_password: str | None = None):
    heading("Setting up PostgreSQL database")

    # Try to create user and database
    if db_password:
        commands = [
            f"CREATE USER liveaszan WITH PASSWORD '{db_password}';",
            "CREATE DATABASE liveaszan OWNER liveaszan;",
            "GRANT ALL PRIVILEGES ON DATABASE liveaszan TO liveaszan;",
        ]
        for cmd in commands:
            result = run(f'psql -U postgres -c "{cmd}"', check=False)
            if result.returncode != 0:
                if "already exists" in (result.stderr or ""):
                    warn(f"Already exists, skipping: {cmd[:40]}...")
                else:
                    warn(f"Could not run: {cmd[:40]}... (you may need to set up the DB manually)")
    else:
        warn("Skipping DB creation (no password generated — .env already existed)")

def setup_prisma():
    heading("Setting up Prisma")
    run("npx prisma generate", cwd=SERVER_DIR)
    success("Prisma client generated")

    print("  Pushing schema to database...")
    result = run("npx prisma db push", cwd=SERVER_DIR, check=False)
    if result.returncode == 0:
        success("Database schema pushed")
    else:
        warn("Could not push schema (database may not be running)")
        print(f"  Error: {result.stderr[:200] if result.stderr else 'unknown'}")
        print("  You can run later: cd server && npx prisma db push")

def seed_database():
    heading("Seeding database with mosque data")
    result = run("npx tsx prisma/seed.ts", cwd=SERVER_DIR, check=False)
    if result.returncode == 0:
        success("Database seeded with mosque data")
        if result.stdout:
            print(f"  {result.stdout.strip()}")
    else:
        warn("Could not seed database (will work once DB is running)")
        print("  You can run later: cd server && npx tsx prisma/seed.ts")

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("\n" + "=" * 60)
    print("  LiveAzan — Setup Script")
    print(f"  Platform: {platform.system()} {platform.machine()}")
    print("=" * 60)

    is_production = "--production" in sys.argv

    # 1. Detect OS and check prerequisites
    detect_os()
    check_python()
    check_node()
    check_postgres()
    check_redis()

    # 2. Install dependencies
    install_dependencies()

    # 3. Generate .env
    db_password = generate_env()

    # 4. Setup database
    setup_database(db_password)

    # 5. Prisma
    setup_prisma()

    # 6. Seed
    seed_database()

    # 7. Summary
    heading("Setup Complete!")
    print("""
  Next steps:

  1. Start the backend:
     cd server && npm run dev

  2. Start the mobile app:
     cd apps/mobile && npx expo start

  3. Start the admin portal:
     cd apps/admin && npm run dev

  URLs:
    Backend API:    http://localhost:3001/api
    Mobile (Expo):  exp://localhost:8081
    Admin Portal:   http://localhost:5174

  Useful commands:
    npm run dev          — Start all services (Turborepo)
    npm run db:seed      — Re-seed mosque data
    npm run db:migrate   — Run database migrations
""")

if __name__ == "__main__":
    main()
