/**
 * Local mosque search — queries the bundled mosque index without network.
 *
 * The index is generated by scripts/generate-mosque-bundle.py from the
 * /data/mosques/ research files and committed to the repo. It is a
 * fallback for when the backend is unavailable; the backend always takes
 * priority when it is running.
 */

import mosqueIndex from "../assets/data/mosques-index.json";
import type { DiscoveredMosque } from "./iqamaDiscovery";
import type { IqamaTimes } from "./mawaqitService";

console.log(`[LocalSearch] mosque index loaded: ${(mosqueIndex as any[]).length} entries`);

interface LocalMosqueRecord {
  id: string;
  name: string;
  type: string;
  address: string;
  city: string;
  province: string;
  country: string;
  latitude: number;
  longitude: number;
  phone?: string | null;
  website?: string | null;
  hasLiveStream: boolean;
  verified: boolean;
  iqamaTimes: IqamaTimes;
  description?: string | null;
  denomination?: string | null;
  hours?: string | null;
  accessInfo?: string | null;
  services?: string[];
  facilities?: string[];
}

/**
 * Return all bundled mosques within `radiusKm` of (lat, lon), sorted by
 * distance ascending.
 */
export function searchLocalMosques(
  lat: number,
  lon: number,
  radiusKm: number
): DiscoveredMosque[] {
  const results = (mosqueIndex as LocalMosqueRecord[])
    .filter((m) => haversineKm(lat, lon, m.latitude, m.longitude) <= radiusKm)
    .map((m) => ({
      id: m.id,
      name: m.name,
      type: m.type as any,
      address: m.address,
      city: m.city,
      province: m.province,
      country: m.country,
      latitude: m.latitude,
      longitude: m.longitude,
      phone: m.phone ?? undefined,
      website: m.website ?? undefined,
      hasLiveStream: m.hasLiveStream,
      verified: m.verified,
      iqamaSource: "manual" as const,
      iqamaLastFetched: undefined,
      discoveredIqama: Object.keys(m.iqamaTimes).length > 0
        ? m.iqamaTimes
        : undefined,
      description: m.description ?? undefined,
      denomination: m.denomination ?? undefined,
      hours: m.hours ?? undefined,
      accessInfo: m.accessInfo ?? undefined,
      services: m.services,
      facilities: m.facilities,
    }))
    .sort(
      (a, b) =>
        haversineKm(lat, lon, a.latitude, a.longitude) -
        haversineKm(lat, lon, b.latitude, b.longitude)
    );
  console.log(`[LocalSearch] searched (${lat.toFixed(4)}, ${lon.toFixed(4)}) r=${radiusKm}km → ${results.length} results`);
  return results;
}

function haversineKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}
